=== geoblacklight/geoblacklight/schema/geoblacklight-schema-aardvark.json
{
  "$schema": "http://json-schema.org/schema#",
  "description": "Schema for GeoBlacklight. See https://opengeometadata.github.io/aardvark/aardvarkMetadata.html for more details.",
  "id": "http://geoblacklight.org/schema/aardvark",
  "title": "GeoBlacklight Schema - Aardvark",
  "type": "object",
  "properties": {
    "dct_title_s": { "type": "string" },
    "dct_alternative_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_description_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_language_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_displayNote_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_creator_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_publisher_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "schema_provider_s": { "type": "string" },
    "gbl_resourceClass_sm": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Datasets", "Maps", "Imagery", "Collections", "Websites", "Web services", "Other"]
      }
    },
    "gbl_resourceType_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_subject_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_theme_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_keyword_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_temporal_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_issued_s": { "type": "string" },
    "gbl_indexYear_im": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "gbl_dateRange_drsim": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_spatial_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "locn_geometry": { "type": "string" },
    "dcat_bbox": { "type": "string" },
    "dcat_centroid": { "type": "string" },
    "dct_relation_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "pcdm_memberOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isPartOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_source_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isVersionOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_replaces_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isReplacedBy_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rights_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rightsHolder_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_license_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_accessRights_s": { "type": "string" },
    "dct_format_s": { "type": "string" },
    "gbl_fileSize_s": { "type": "string" },
    "gbl_wxsIdentifier_s": { "type": "string" },
    "dct_references_s": { "type": "string" },
    "id": { "type": "string" },
    "dct_identifier_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_mdModified_dt": {
      "type": "string",
      "format": "date-time"
    },
    "gbl_mdVersion_s": {
      "type": "string",
      "const": "Aardvark"
    },
    "gbl_suppressed_b": { "type": ["string", "boolean"] },
    "gbl_georeferenced_b": { "type": ["string", "boolean"] }
  },
  "required": ["id", "dct_title_s", "gbl_resourceClass_sm", "dct_accessRights_s", "gbl_mdVersion_s"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/no_locn_geometry.json
{
  "dct_title_s": "University of Minnesota Digital Conservancy DRUM",
  "dct_alternative_sm": ["no_locn_geometry"],
  "dct_description_sm": [
    "This is a collection level record without spatial coordinates or a Geometry Type (GBL Metadata 1.0). ",
    "DRUM is a publicly available collection of digital research data generated by University of Minnesota researchers, students, and staff. Anyone can search and download the data housed in the repository, instantly or by request."
  ],
  "dct_publisher_sm": ["University of Minnesota Digital Conservancy"],
  "schema_provider_s": "University of Minnesota",
  "gbl_resourceClass_sm": ["Collections"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_accessRights_s": "Public",
  "dct_references_s": "{\"http://schema.org/url\":\"https://conservancy.umn.edu/handle/11299/166578\"}",
  "id": "05d-03-noGeomType",
  "gbl_mdModified_dt": "2021-06-11T18:36:48Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/esri-dynamic-layer-single-layer.json
{
  "dct_title_s": "Abandoned Quarries: Indiana",
  "dct_alternative_sm": ["esri-dynamic-layer-single-layer"],
  "dct_description_sm": [
    "ArcGIS Dynamic Map Layer with single layer indicated. ",
    "QUARRIES_ABANDONED_IN was derived from a comma-delimited text file named \"QUALOC.TXT\" contained on the following CD-ROM publication: Hasenmueller, W.A., and Ault, C.H., 2001, Abandoned Industrial Minerals Quarries in Indiana, 2nd Edition, Digital Version, Computer Database 2, Indiana Geological Survey. The field named \"QUANUM\" can be used to link this data to the following tables available in the publication cited above: bibliography (QUAREF.TXT), history of operation (QUAHIS.TXT), and stratigraphy (QUASTR.TXT). It contains all abandoned quarry locations within QUALOC.TXT that have locational information that is adequate to determine UTM coordinate values."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Indiana Geological Survey"],
  "dct_publisher_sm": ["Indiana Geological Survey"],
  "schema_provider_s": "Purdue University",
  "gbl_resourceClass_sm": ["Datasets", "Web services"],
  "gbl_resourceType_sm": ["Point data"],
  "dcat_theme_sm": ["Geology"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2003"],
  "dct_issued_s": "2003-05-30",
  "gbl_indexYear_im": [2003],
  "gbl_dateRange_drsim": ["[2003 TO 2003]"],
  "dct_spatial_sm": ["Indiana"],
  "locn_geometry": "ENVELOPE(-87.9324,-86.2569,39.8521,37.8626)",
  "dcat_bbox": "ENVELOPE(-87.9324,-86.2569,39.8521,37.8626)",
  "dcat_centroid": "38.85735,-87.09465",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://maps.indiana.edu/download/Geology/Industrial_Minerals_Quarries_Abandoned.zip\",\"http://www.opengis.net/cat/csw/csdgm\":\"https://maps.indiana.edu/metadata/Geology/Industrial_Minerals_Quarries_Abandoned.xml\",\"http://schema.org/url\":\"http://maps.indiana.edu/previewMaps/Geology/Industrial_Minerals_Quarries_Abandoned.html\",\"urn:x-esri:serviceType:ArcGIS#DynamicMapLayer\":\"https://maps.indiana.edu/arcgis/rest/services/Geology/Industrial_Minerals_Quarries_Abandoned/MapServer/0\"}",
  "id": "4669301e-b4b2-4c8b-bf40-01b968a2865b",
  "dct_identifier_sm": ["4669301e-b4b2-4c8b-bf40-01b968a2865b"],
  "gbl_mdModified_dt": "2021-06-01T22:14:15Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/umn_state_result1.json
{
  "dct_title_s": "1:100k Digital Raster Graphic - Collars Removed: Minnesota",
  "dct_alternative_sm": ["umn_state_result1"],
  "dct_description_sm": [
    "Bounding box of state area and static image in references. ",
    "A digital raster graphic (DRG) is a scanned image of an U.S. Geological Survey (USGS) standard series topographic map, including all map collar information. The image inside the map neatline is georeferenced to the surface of the earth and fit to the Universal Transverse Mercator projection. The horizontal positional accuracy and datum of the DRG matches the accuracy and datum of the source map. The map is scanned at a minimum resolution of 250 dots per inch.  DRG's are created by scanning published paper maps on high-resolution scanners.  The raster image is georeferenced and fit to the UTM projection.  Colors are standardized to remove scanner limitations and artifacts.  The average data set size is about 6 megabytes in Tagged Image File Format (TIFF) with PackBits compression. DRG's can be easily combined with other digital cartographic products such as digital elevation models (DEM) and digital orthophoto quadrangles (DOQ).  DRG's are stored as rectified TIFF files in geoTIFF format. GeoTIFF is a relatively new TIFF image storage format that incorporates georeferencing information in the header. This allows software, such as ArcView, ARC/INFO, or EPPL7 to reference the image without an additional header or world file.  Within the Minnesota Department of Natural Resources Core GIS data set the DRG's have been processed to be in compliance with departmental data standards (UTM Extended Zone 15, NAD83 datum) and the map collar information has been removed to facilitate the display of the DRG's in a seamless fashion.  These DRG's were clipped and transformed to UTM Zone 15 using EPPL7 Raster GIS."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["U.S. Geological Survey (USGS) and Minnesota Department of Natural Resources (DNR)"],
  "dct_publisher_sm": ["Minnesota Department of Natural Resources (DNR)"],
  "schema_provider_s": "University of Minnesota",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Raster data"],
  "dcat_theme_sm": ["Imagery"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2015"],
  "dct_issued_s": "2015-11-18",
  "gbl_indexYear_im": [2015],
  "gbl_dateRange_drsim": ["[2015 TO 2015]"],
  "dct_spatial_sm": ["Minnesota"],
  "locn_geometry": "ENVELOPE(-97.612501,-88.842351,49.464145,42.906949)",
  "dcat_bbox": "ENVELOPE(-97.612501,-88.842351,49.464145,42.906949)",
  "dcat_centroid": "46.185547,-93.227426",
  "dct_accessRights_s": "Public",
  "dct_format_s": "ArcGRID",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"ftp://gdrs.dnr.state.mn.us/gdrs/data/pub/us_mn_state_dnr/fgdb_base_usgs_scanned_topo_100k_drg.zip\",\"http://schema.org/url\":\"https://gisdata.mn.gov/dataset/2eddde2f-c222-41ca-bd07-2fd74a21f4de\"}",
  "id": "2eddde2f-c222-41ca-bd07-2fd74a21f4de",
  "dct_identifier_sm": ["2eddde2f-c222-41ca-bd07-2fd74a21f4de"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/b1g_wabash_child_17.json
{
  "dct_title_s": "Wabash Aerial (17): Indiana, 1929",
  "dct_description_sm": [
    "The images represented here are the raster orthophoto set collected by remote sensing of 25 aerial images  owned by EAS library. Each aerial image was up to 450MB, 400dpi, grayscale. These images can be viewed and performed in the using either ArcGIS Desktop or QGIS (user choice), referencing against a number of known mapsets like the 2005 Indiana Orthophoto setand USGS DRGs. The geographic coordinate system reference of the maps included are applied in GCS_WGS_1984."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Brock & Weymouth Inc.", "United States Engineer Office"],
  "schema_provider_s": "Purdue University",
  "gbl_resourceClass_sm": ["Imagery"],
  "dcat_theme_sm": ["Imagery"],
  "dcat_keyword_sm": ["Universities", "Campuses"],
  "dct_temporal_sm": ["1929"],
  "dct_issued_s": "2015-11-02",
  "gbl_indexYear_im": [1929],
  "gbl_dateRange_drsim": ["[1929 TO 1929]"],
  "dct_spatial_sm": ["Indiana"],
  "locn_geometry": "ENVELOPE(-87.4646,-87.3186,39.673,39.5987)",
  "dcat_bbox": "ENVELOPE(-87.4646,-87.3186,39.673,39.5987)",
  "dcat_centroid": "39.635850000000005,-87.39160000000001",
  "pcdm_memberOf_sm": ["dc8c18df-7d64-4ff4-a754-d18d0891187d"],
  "dct_isPartOf_sm": ["09d-01", "eee6150b-ce2f-4837-9d17-ce72a0c1c26f"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "GeoTIFF",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://mapsweb.lib.purdue.edu/datasets/Wabash1929/wabashAerial_17.tif.zip\",\"urn:x-esri:serviceType:ArcGIS#ImageMapLayer\":\"https://mapsweb.lib.purdue.edu/arcgis/rest/services/Purdue/wabashaerial/ImageServer\",\"http://schema.org/url\":\"https://mapsweb.lib.purdue.edu/wabashriver/\"}",
  "id": "33ecd1bd-c532-422c-8996-d8c1800aed5b",
  "dct_identifier_sm": ["33ecd1bd-c532-422c-8996-d8c1800aed5b"],
  "gbl_mdModified_dt": "2022-05-31T13:44:06Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/princeton-child4.json
{
  "dct_title_s": "Princeton, Mercer County, New Jersey (Sheet 4)",
  "dct_alternative_sm": ["princeton-child4"],
  "dct_description_sm": [
    "Child record for testing the gbl_suppressed_b property. ",
    "Title taken from sheet 1 of 1927 map. \"Feb. 1885.\" Includes location map and key. Oriented with the north to the upper left."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Sanborn Map Company"],
  "dct_publisher_sm": ["New York : Sanborn Map & Publishing Co., Limited, 1885."],
  "schema_provider_s": "Princeton",
  "gbl_resourceClass_sm": ["Maps"],
  "dct_subject_sm": ["Real property-New Jersey-Princeton-Maps", "Princeton (N.J.)-Maps"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "locn_geometry": "ENVELOPE(-74.68,-74.63,40.37,40.33)",
  "dcat_bbox": "ENVELOPE(-74.68,-74.63,40.37,40.33)",
  "dcat_centroid": "40.349999999999994,-74.655",
  "dct_source_sm": ["princeton-1r66j405w"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "TIFF",
  "gbl_wxsIdentifier_s": "public-figgy:p-b6ba3091-fcf4-4d2d-9d6a-df7df5c8c589",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://figgy.princeton.edu/downloads/b6ba3091-fcf4-4d2d-9d6a-df7df5c8c588/file/ff89fcc8-e61b-4b27-938f-a03e63d4f5f1\",\"http://iiif.io/api/image\":\"https://libimages1.princeton.edu/loris/figgy_prod/5a%2F20%2F58%2F5a20585db50d44959fe5ae44821fd174%2Fintermediate_file.jp2/info.json\",\"http://schema.org/url\":\"https://catalog.princeton.edu/catalog/4266648\",\"http://iiif.io/api/presentation#manifest\":\"https://figgy.princeton.edu/concern/scanned_maps/2806e4cf-effc-4827-b116-952dfe776d14/manifest\"}",
  "id": "princeton-n009w382v-fake2",
  "dct_identifier_sm": ["ark:/88435/n009w382v", "HMC04 (Princeton)"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark",
  "gbl_suppressed_b": true
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/baruch_documentation_download.json
{
  "dct_title_s": "2015 New York City Subway Complexes and Ridership",
  "dct_alternative_sm": ["baruch_documentation_download"],
  "dct_description_sm": [
    "Point dataset with WMS and WFS, documentation download, and two parent records. ",
    "The subway complexes layer was created to represent ridership data for the NYC subway system (Metropolitan Transportation Authority, or MTA). This layer is a subset of the subway stations layer (nyu_2451_34503) that has been combined with MTA statistics on ridership; it was originally created in August 2012 and has been updated annually. Ridership data is not available for each individual subway station, as many stations are linked via common entrances and passageways where transfers are free, and because ridership data is not collected for the Staten Island Railway stations. This layer was created by choosing an individual station from nyu_2451_34503 to represent the entire complex, and modifying the station name and train fields appropriately. It should be used for mapping ridership data or for analysis that requires this data, and not for specifying actual station locations or measuring distances. There are 421 complexes, and the field station_ct indicates how many stations are part of a complex. Annual, average weekday, and average weekend ridership is provided for 2007 to 2014. The unique ID is complex_id, which was created by alphabetizing the complexes by borough and station name and assigning a sequential number to a borough prefix. This layer does not include the new 34th St - 11 Av station on the 7 line; it will be updated in summer 2016 once ridership data becomes available. This layer was created as part of the NYC Geodatabase (NYC GDB) project, a resource designed for basic geographic analysis and thematic mapping within the five boroughs of New York City."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["GIS Lab, Newman Library, Baruch CUNY"],
  "dct_publisher_sm": ["Newman Library (Bernard M. Baruch College)"],
  "schema_provider_s": "Baruch CUNY",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Point data"],
  "dct_subject_sm": ["Subway stations", "Urban transportation", "Local transit", "Commuting"],
  "dcat_theme_sm": ["Transportation"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2015"],
  "dct_issued_s": "2016-01-15",
  "gbl_indexYear_im": [2015],
  "gbl_dateRange_drsim": ["[2015 TO 2015]"],
  "dct_spatial_sm": [
    "New York, New York",
    "Bronx County, New York",
    "Kings County, New York",
    "New York County, New York",
    "Queens County, New York",
    "Borough of Bronx, New York",
    "Borough of Brooklyn, New York",
    "Borough of Manhattan, New York",
    "Borough of Queens, New York"
  ],
  "locn_geometry": "ENVELOPE(-74.030876,-73.755405,40.903125,40.576127)",
  "dcat_centroid": "40.739626,-73.8931405",
  "dct_source_sm": ["nyu_2451_34635", "nyu_2451_34636"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "gbl_wxsIdentifier_s": "sdr:nyu_2451_34502",
  "dct_references_s": "{\"http://lccn.loc.gov/sh85035852\":\"https://archive.nyu.edu/retrieve/74755/nyu_2451_34502_doc.zip\",\"http://schema.org/downloadUrl\":\"https://archive.nyu.edu/retrieve/74701/nyu_2451_34502.zip\",\"http://schema.org/url\":\"http://hdl.handle.net/2451/34502\",\"http://www.isotc211.org/schemas/2005/gmd/\":\"http://metadata.geo.nyu.edu/records/edu.nyu/handle/2451/34502/iso19139.xml\",\"http://www.opengis.net/def/serviceType/ogc/wfs\":\"https://maps-public.geo.nyu.edu/geoserver/sdr/wfs\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://maps-public.geo.nyu.edu/geoserver/sdr/wms\"}",
  "id": "nyu_2451_34502",
  "dct_identifier_sm": ["http://hdl.handle.net/2451/34502"],
  "gbl_mdModified_dt": "2021-06-01T22:14:15Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/restricted-line.json
{
  "dct_title_s": "10 Meter Contours: Russian River Basin, California",
  "dct_alternative_sm": ["restricted-line"],
  "dct_description_sm": [
    "Restricted line layer with WFS, WMS and metadata in MODS and ISO 19139. ",
    "This line shapefile contains contours that were derived from a mosiac of 10 meter digital elevation models for the extent of the Russian River basin, located in Sonoma and Mendocino Counties, California.This layer can be used for watershed analysis and planning in the Russian River region of California."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["United States. National Oceanic and Atmospheric Administration", "Circuit Rider Productions"],
  "dct_publisher_sm": ["Circuit Rider Productions"],
  "schema_provider_s": "Stanford",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Line data"],
  "dct_subject_sm": ["Contours (Cartography)", "Elevation", "Inland Waters"],
  "dcat_theme_sm": ["Elevation", "Inland Waters"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2002"],
  "dct_issued_s": "2002",
  "gbl_indexYear_im": [2002],
  "gbl_dateRange_drsim": ["[2002 TO 2002]"],
  "dct_spatial_sm": ["Sonoma County (Calif.)", "Mendocino County (Calif.)"],
  "locn_geometry": "ENVELOPE(-123.387366,-122.52958,39.398403,38.302994)",
  "dcat_bbox": "ENVELOPE(-123.387366,-122.52958,39.398403,38.302994)",
  "dcat_centroid": "38.8506985,-122.958473",
  "dct_rights_sm": [
    "These data are licensed by Stanford Libraries and are available to Stanford University affiliates only. Affiliates are limited to current faculty, staff and students. These data may not be reproduced or used for any purpose without permission. For more information please contact brannerlibrary@stanford.edu"
  ],
  "dct_accessRights_s": "Restricted",
  "dct_format_s": "Shapefile",
  "gbl_wxsIdentifier_s": "druid:cg357zz0321",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://stacks.stanford.edu/file/druid:cg357zz0321/data.zip\",\"http://schema.org/url\":\"http://purl.stanford.edu/cg357zz0321\",\"http://www.isotc211.org/schemas/2005/gmd/\":\"https://raw.githubusercontent.com/OpenGeoMetadata/edu.stanford.purl/master/cg/357/zz/0321/iso19139.xml\",\"http://www.loc.gov/mods/v3\":\"http://purl.stanford.edu/cg357zz0321.mods\",\"http://www.opengis.net/def/serviceType/ogc/wfs\":\"https://geowebservices-restricted.stanford.edu/geoserver/wfs\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://geowebservices-restricted.stanford.edu/geoserver/wms\"}",
  "id": "stanford-cg357zz0321",
  "dct_identifier_sm": ["http://purl.stanford.edu/cg357zz0321"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/baruch_ancestor2.json
{
  "dct_title_s": "2016 NYC Geodatabase, ArcGIS Version (jan2016)",
  "dct_alternative_sm": ["baruch_ancestor2"],
  "dct_description_sm": [
    "Geodatabase with documentation download. Referenced as parent. ",
    "The NYC Geodatabase (nyc_gdb) is a resource designed for basic geographic analysis and thematic mapping within the five boroughs of New York City. It contains geographic features and data compiled from several public sources. Subsets of large features like water, greenspace, and public facilities were created and Census geographies like tracts, ZCTAs, and PUMAs were geoprocessed to create land-based boundaries. Census data from the 2010 Census, American Community Survey (ACS), and ZIP Code Business Patterns are stored in tables that can be easily related to geographic features. Transit and public facility point data were gathered from several city agencies and transformed into spatial data that can be used for reference or analysis for measuring distance, drawing buffers, or counting features within areas. The data is provided in ESRI Geodatabase format."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["GIS Lab, Newman Library, Baruch CUNY"],
  "dct_publisher_sm": ["Newman Library (Bernard M. Baruch College)"],
  "schema_provider_s": "Baruch CUNY",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Mixed data"],
  "dct_subject_sm": ["Boroughs", "Counties"],
  "dcat_theme_sm": ["Boundaries"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2010, 2016"],
  "dct_issued_s": "2016-01-15",
  "gbl_indexYear_im": [2010],
  "gbl_dateRange_drsim": ["[2010 TO 2016]"],
  "dct_spatial_sm": [
    "New York, New York",
    "Bronx County, New York",
    "Kings County, New York",
    "New York County, New York",
    "Queens County, New York",
    "Richmond County, New York",
    "Borough of Bronx, New York",
    "Borough of Brooklyn, New York",
    "Borough of Manhattan, New York",
    "Borough of Queens, New York",
    "Borough of Staten Island, New York"
  ],
  "locn_geometry": "ENVELOPE(-74.255895,-73.700272,40.915282,40.495929)",
  "dcat_bbox": "ENVELOPE(-74.255895,-73.700272,40.915282,40.495929)",
  "dcat_centroid": "40.7056055,-73.9780835",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Geodatabase",
  "gbl_wxsIdentifier_s": "sdr:nyu_2451_34636",
  "dct_references_s": "{\"http://lccn.loc.gov/sh85035852\":\"https://archive.nyu.edu/retrieve/74857/nyu_2451_34636_doc.zip\",\"http://schema.org/downloadUrl\":\"https://archive.nyu.edu/retrieve/74856/nyu_2451_34636.zip\",\"http://schema.org/url\":\"http://hdl.handle.net/2451/34636\"}",
  "id": "nyu_2451_34636",
  "dct_identifier_sm": ["http://hdl.handle.net/2451/34636"],
  "gbl_mdModified_dt": "2021-06-01T22:14:15Z",
  "gbl_mdVersion_s": "Aardvark"
}
