=== geoblacklight/geoblacklight/schema/geoblacklight-schema-aardvark.json
{
  "$schema": "http://json-schema.org/schema#",
  "description": "Schema for GeoBlacklight. See https://opengeometadata.github.io/aardvark/aardvarkMetadata.html for more details.",
  "id": "http://geoblacklight.org/schema/aardvark",
  "title": "GeoBlacklight Schema - Aardvark",
  "type": "object",
  "properties": {
    "dct_title_s": { "type": "string" },
    "dct_alternative_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_description_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_language_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_displayNote_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_creator_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_publisher_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "schema_provider_s": { "type": "string" },
    "gbl_resourceClass_sm": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Datasets", "Maps", "Imagery", "Collections", "Websites", "Web services", "Other"]
      }
    },
    "gbl_resourceType_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_subject_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_theme_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_keyword_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_temporal_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_issued_s": { "type": "string" },
    "gbl_indexYear_im": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "gbl_dateRange_drsim": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_spatial_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "locn_geometry": { "type": "string" },
    "dcat_bbox": { "type": "string" },
    "dcat_centroid": { "type": "string" },
    "dct_relation_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "pcdm_memberOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isPartOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_source_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isVersionOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_replaces_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isReplacedBy_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rights_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rightsHolder_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_license_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_accessRights_s": { "type": "string" },
    "dct_format_s": { "type": "string" },
    "gbl_fileSize_s": { "type": "string" },
    "gbl_wxsIdentifier_s": { "type": "string" },
    "dct_references_s": { "type": "string" },
    "id": { "type": "string" },
    "dct_identifier_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_mdModified_dt": {
      "type": "string",
      "format": "date-time"
    },
    "gbl_mdVersion_s": {
      "type": "string",
      "const": "Aardvark"
    },
    "gbl_suppressed_b": { "type": ["string", "boolean"] },
    "gbl_georeferenced_b": { "type": ["string", "boolean"] }
  },
  "required": ["id", "dct_title_s", "gbl_resourceClass_sm", "dct_accessRights_s", "gbl_mdVersion_s"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/no_spatial.json
{
  "dct_title_s": "ASTER Global Emissivity Dataset 1-kilometer V003 - AG1KM",
  "dct_alternative_sm": ["no_spatial"],
  "dct_description_sm": [
    "File without geometry type or locn_geometry (will cause error). ",
    "The Advanced Spaceborne Thermal Emission and Reflection radiometer Global Emissivity Database (ASTER GED) was developed by the National Aeronautics and Space Administration's (NASA) Jet Propulsion Laboratory (JPL), California Institute of Technology. The North America portion of this collection was formerly called the North American ASTER Land Surface Emissivity Database (NAALSED) - a seasonal dataset consisting of mean summer (J-A-S) and winter (J-F-M) products. ASTER GED products are output on 1degree x 1 degree grids at 100-meter or 1-kilometer spatial resolution (nominal) and include the mean emissivity and standard deviation for all 5 ASTER thermal infrared bands, mean land surface temperature (LST) and standard deviation, a re-sampled ASTER GDEM (not included in the North America Winter products), land-water mask, mean Normalized Difference Vegetation Index (NDVI) and standard deviation, latitude, longitude, and observation count. Additional ASTER GED product information is available at https://lpdaac.usgs.gov/products/community_products_table. Product tiles are available in HDF and binary format and may be downloaded via HTTP by visiting the following data clients: NASA Reverb (http://reverb.echo.nasa.gov), LP DAAC Data Pool (http://e4ftl01.cr.usgs.gov/ASTT/), or EarthExplorer (http://earthexplorer.usgs.gov)."
  ],
  "schema_provider_s": "U.S. Geological Survey, Department of the Interior",
  "gbl_resourceClass_sm": ["Imagery"],
  "dct_subject_sm": [
    "Land surface temperature",
    "U.S. Geological survey (USGS)",
    "Earth observing system",
    "Land processes distributed active archive center (LPDAAC)",
    "Aster",
    "Normalized difference vegetation index",
    "Terra",
    "Image map",
    "Emissivity"
  ],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_accessRights_s": "Public",
  "dct_references_s": "{}",
  "id": "aster-global-emissivity-dataset-1-kilometer-v003-ag1kmcad20",
  "dct_identifier_sm": ["c0515c4e-97dc-4fff-82cb-f65144482631"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/esri-wms-layer.json
{
  "dct_title_s": "Agriculture Census: Indiana, 1997",
  "dct_alternative_sm": ["esri-wms-layer"],
  "dct_description_sm": [
    "Dataset with ArcGIS Dynamic Map Layer, ArcGIS WMS, and direct download. ",
    "USGS National Atlas metadata states \"This data set portrays the National Agricultural Statistics Service, U.S. Department of Agriculture's 1997 Census data for the United States, presented by county. There are 25 categories of data which include information about farms, crops, livestock, values of products, and farm operator characteristics.\""
  ],
  "dct_creator_sm": [
    "(creation): U.S. Geological Survey",
    "(selection/conversion): Bernardin, Lochmueller and Associates"
  ],
  "dct_publisher_sm": ["Bernardin, Lochmueller and Associates"],
  "schema_provider_s": "Purdue University",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Mixed data"],
  "dct_subject_sm": ["Agriculture"],
  "dcat_theme_sm": ["Farming"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["1972-1997"],
  "dct_issued_s": "2003-01-28",
  "gbl_indexYear_im": [1972],
  "gbl_dateRange_drsim": ["[1972 TO 1997]"],
  "dct_spatial_sm": ["Indiana"],
  "locn_geometry": "ENVELOPE(-88.1607,-84.6882,41.7753,37.7554)",
  "dcat_bbox": "ENVELOPE(-88.1607,-84.6882,41.7753,37.7554)",
  "dcat_centroid": "39.76,-86.42",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "gbl_wxsIdentifier_s": "0",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://schema.org/downloadUrl:https://maps.indiana.edu/download/Environment/Agriculture_Census.zip\",\"http://schema.org/url\":\"http://indianamap.org/\",\"http://www.isotc211.org/schemas/2005/gmd/\":\"https://opengeometadata.github.io/edu.purdue/f0/82/ac/b1b01e4a089126fd62a23fd9aa/iso19139.xml\",\"urn:x-esri:serviceType:ArcGIS#DynamicMapLayer\":\"https://maps.indiana.edu/arcgis/rest/services/Environment/Agriculture_Census/MapServer\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://maps.indiana.edu/arcgis/services/Environment/Agriculture_Census/MapServer/WMSServer\"}",
  "id": "purdue-urn-f082acb1-b01e-4a08-9126-fd62a23fd9aa",
  "dct_identifier_sm": ["urn-f082acb1-b01e-4a08-9126-fd62a23fd9aa"],
  "gbl_mdModified_dt": "2021-06-01T22:14:15Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/public_iiif_princeton.json
{
  "dct_title_s": "The provinces of New York and New Jersey, with part of Pensilvania, and the Province of Quebec : drawn by Major Holland, Surveyor General, of the Northern District in America. Corrected and improved, from the original materials, by Governr. Pownall, Member of Parliament, 1776",
  "dct_alternative_sm": ["public_iiif_princeton"],
  "dct_description_sm": [
    "Scanned map with IIIF. ",
    "Partly colored. Relief shown pictorially. Shows administrative divisions. From Thomas Jefferys's The American atlas, or, A geographical description of the whole continent of America (London : Printed by R. Sayer and Bennett, 1778). Insets: A chart of the mouth of Hudson's River, from Sandy Hook to New York. A plan of the city of New York. Plan of Amboy, with its environs, from an actual survey."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Rogers, Henry Darwin", "Pownall, Thomas"],
  "dct_publisher_sm": ["London, Robt. Sayer & John Bennett"],
  "schema_provider_s": "Princeton",
  "gbl_resourceClass_sm": ["Maps"],
  "gbl_resourceType_sm": ["Raster data"],
  "dct_subject_sm": ["New York (State)‒Maps", "New Jersey‒Maps"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["1778"],
  "dct_issued_s": "1904-11-12",
  "gbl_indexYear_im": [1778],
  "gbl_dateRange_drsim": ["[1778 TO 1778]"],
  "dct_spatial_sm": ["New York (State)", "New Jersey", "Pennsylvania"],
  "locn_geometry": "ENVELOPE(-76.3394,-72.1916,46.5798,38.6693)",
  "dcat_bbox": "ENVELOPE(-76.3394,-72.1916,46.5798,38.6693)",
  "dcat_centroid": "42.62455,-74.2655",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Raster",
  "gbl_wxsIdentifier_s": "02870w62c",
  "dct_references_s": "{\"http://iiif.io/api/image\":\"https://iiif-cloud.princeton.edu/iiif/2/6c%2F52%2F12%2F6c5212e81bc845f59bb1cdc740a88bad%2Fintermediate_file/info.json\",\"http://schema.org/url\":\"http://arks.princeton.edu/ark:/88435/02870w62c\"}",
  "id": "princeton-02870w62c",
  "dct_identifier_sm": ["http://arks.princeton.edu/ark:/88435/02870w62c"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/esri-tiled_map_layer.json
{
  "dct_title_s": "Minnesota Land Cover Classification and Impervious Surface Area by Landsat and Lidar (2013 Update)",
  "dct_description_sm": [
    "This is a 15-meter raster dataset of a land cover and impervious surface classification for 2013, level two classification. The classification was created using a combination of multitemporal Landsat 8 data and LiDAR data with Object-based image analysis. By using objects instead of pixels we were able to utilize multispectral data along with spatial and contextual information of objects such as shape, size, texture and LiDAR-derived metrics to distinguish different land cover types. While OBIA has become the standard procedure for classification of high resolution imagery we found that it works equally well with Landsat imagery. For the objects classified as urban or developed, a regression model relating the Landsat greenness variable to percent impervious was developed to estimate and map the percent impervious surface area at the pixel level."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Bauer, Marvin E.", "Knight, Joe F.", "Rampi, Lian P."],
  "schema_provider_s": "University of Minnesota",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Vector data", "Raster data", "LiDAR"],
  "dcat_theme_sm": ["Imagery"],
  "dcat_keyword_sm": ["Lidar", "Landsat Satellites", "Land cover", "2022-creator-sprint"],
  "dct_temporal_sm": ["2013"],
  "dct_issued_s": "2016-08-03",
  "gbl_indexYear_im": [2013],
  "gbl_dateRange_drsim": ["[2013 TO 2013]"],
  "dct_spatial_sm": ["Minnesota"],
  "locn_geometry": "POLYGON((-97.23 49.37, -89.53 49.37, -89.53 43.5, -97.23 43.5, -97.23 49.37))",
  "dcat_bbox": "ENVELOPE(-97.23,-89.53,49.37,43.5)",
  "dcat_centroid": "46.435,-93.38",
  "pcdm_memberOf_sm": ["dc8c18df-7d64-4ff4-a754-d18d0891187d"],
  "dct_isPartOf_sm": ["05d-03"],
  "dct_rights_sm": ["https://conservancy.umn.edu/pages/drum/policies/#terms-of-use"],
  "dct_license_sm": ["http://creativecommons.org/publicdomain/zero/1.0/"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "GeoTIFF",
  "dct_references_s": "{\"http://lccn.loc.gov/sh85035852\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Classification%20scheme%20for%20Level%201%20and%202%20land%20cover%20classes%202013.pdf\",\"http://schema.org/downloadUrl\":[{\"label\":\"Original GeoTIFF\",\"url\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Statewide_FinalMap_2013_2014_v2.zip\"}],\"http://www.opengis.net/cat/csw/csdgm\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Statewide_LandCoverMetadata_MN_2013_v2.xml\",\"http://www.w3.org/1999/xhtml\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Statewide_LandCover_Metadata_MN_2013_v2.html\",\"http://schema.org/url\":\"http://doi.org/10.13020/D6JP4S\",\"urn:x-esri:serviceType:ArcGIS#TiledMapLayer\":\"https://tiles.arcgis.com/tiles/8df8p0NlLFEShl0r/arcgis/rest/services/mn_landcover_impervious_2013v2_tiles/MapServer\"}",
  "id": "31567cf1-bad8-4bc5-8d57-44b96c207ecc",
  "dct_identifier_sm": ["http://doi.org/10.13020/D6JP4S", "http://hdl.handle.net/11299/181555"],
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/wmts-single-layer.json
{
  "gbl_mdVersion_s": "Aardvark",
  "dct_identifier_sm": ["ark:/99999/fk4544658v"],
  "id": "princeton-fk4544658v-wmts",
  "dct_title_s": "The Balkans [and] Turkey : G.S.G.S. no. 2097 / War Office. General Staff. Geographical Section (WMTS Fixture)",
  "locn_geometry": "ENVELOPE(19.333333, 29.333333, 43.083333, 39.75)",
  "dcat_bbox": "ENVELOPE(19.333333, 29.333333, 43.083333, 39.75)",
  "schema_provider_s": "Princeton",
  "dct_accessRights_s": "Public",
  "dct_description_sm": [
    "Relief shown by contours approximately 100 feet interval, spot heights, and shading. Title varies; some sheets are titled \"Turkey\". Shows international boundaries, railways, 2 categories of roads, telegraph lines, places of worship, ruins. Constantinople latest edition map has a glossary."
  ],
  "dct_creator_sm": ["Great Britain. War Office. General Staff. Geographical Section"],
  "dct_language_sm": ["eng"],
  "dct_publisher_sm": ["[London] : War Office. General Staff. Geographical Section. General Staff, 1908-25."],
  "dct_subject_sm": ["Balkan Peninsula Maps", "Turkey Maps", "Topographic Maps"],
  "dct_spatial_sm": ["Balkan Peninsula", "Turkey"],
  "dct_issued_s": "1908",
  "gbl_indexYear_im": [1908],
  "gbl_mdModified_dt": "2022-02-03T22:13:40Z",
  "gbl_wxsIdentifier_s": "mosaic",
  "dct_references_s": "{\"http://schema.org/url\":\"https://catalog.princeton.edu/catalog/99125413918506421\",\"http://schema.org/thumbnailUrl\":\"https://figgy-staging.princeton.edu/downloads/6b55d939-7188-4bce-9550-0ac535441f22/file/9042b887-da2e-4aa9-9ca5-d3ba77f440c4\",\"http://iiif.io/api/image\":\"https://iiif-cloud-staging.princeton.edu/iiif/2/05%2F71%2F04%2F0571046f9c7149a3b950899323f70788%2Fintermediate_file/info.json\",\"http://iiif.io/api/presentation#manifest\":\"https://figgy-staging.princeton.edu/concern/scanned_maps/2a91d82c-541c-426c-b787-cc62afe8f248/manifest\",\"http://www.opengis.net/def/serviceType/ogc/wmts\":\"https://map-tiles-staging.princeton.edu/2a91d82c541c426cb787cc62afe8f248/mosaicjson/WMTSCapabilities.xml\"}",
  "gbl_resourceClass_sm": ["Maps", "Web services"],
  "gbl_resourceType_sm": ["Military maps", "Topographic maps"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/actual-papermap1.json
{
  "dct_title_s": "1:1 500 000 series [cartographic material] : tectonic map of Britain, Ireland and adjacent areas / British Geological Survey ; Geological Survey of Ireland ; Geological Survey of Northern Ireland.",
  "dct_alternative_sm": ["actual-papermap1"],
  "dct_description_sm": [
    "Nondigitized paper map with a link to a library catalog. ",
    "Panel title. Depths shown by isolines. \"Geological map [copyright] NERC 1996.\" Also available on flat sheet. \"Sheet 1\"--on panel. Includes text, notes, organizations\\' logos, and ancillary map of \"Orogenic terranes of Britain, Ireland and surrounding seas.\""
  ],
  "dct_language_sm": ["eng"],
  "dct_publisher_sm": ["British Geological Survey"],
  "schema_provider_s": "MIT",
  "gbl_resourceClass_sm": ["Maps"],
  "dcat_keyword_sm": ["Paper map", "GBL Fixture records"],
  "dct_temporal_sm": ["1996"],
  "dct_issued_s": "1905-06-22",
  "gbl_indexYear_im": [1996],
  "gbl_dateRange_drsim": ["[1996 TO 1996]"],
  "locn_geometry": "ENVELOPE(-13,4,62,49)",
  "dcat_bbox": "ENVELOPE(-13,4,62,49)",
  "dcat_centroid": "55.5,-4.5",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Paper",
  "gbl_wxsIdentifier_s": "MIT:001145244",
  "dct_references_s": "{\"http://schema.org/url\":\"http://library.mit.edu/item/001145244\"}",
  "id": "mit-001145244",
  "dct_identifier_sm": ["urn:arrowsmith.mit.edu:MIT.001145244"],
  "gbl_mdModified_dt": "2021-06-11T18:30:23Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/public_cog_princeton.json
{
  "id": "princeton-dc7h14b252v",
  "dct_identifier_sm": ["ark:/88435/dc7h14b252v"],
  "dct_title_s": "Map illustrating the journey of the Pundit Nain Singh through Great Tibet from Ladákh to Assam [cartographic material] : to accompany the paper by Captn. H. Trotter R.E. / [engraved by] Edwd. Weller. (geotiff)",
  "dct_description_sm": [
    "Relief shown by hachures and spot heights. The Pundit's route is colored red. Routes of previous explorers and major roads are also shown. Romanized name of Indian explorer: Nain Singh Rawat. British boundaries and approximate boundary between Nepal and Tibet are shown. Includes glossary of local terms for geographic features. From: The Journal of the Royal Geographical Society of London. Vol. 47, (1877), pp. 86-136; held in Firestone Library. Call number: G7 .J687 v.47 1877"
  ],
  "dct_language_sm": ["en"],
  "dct_publisher_sm": [
    "London: published for the Journal of the Royal Geographical Society by J. Murray, Albemarle Street, 1877."
  ],
  "gbl_resourceClass_sm": ["Maps"],
  "gbl_resourceType_sm": ["Raster data"],
  "gbl_resourceClass_sm": ["Maps"],
  "gbl_indexYear_im": [1877],
  "dct_spatial_sm": ["Himalaya Mountains"],
  "locn_geometry": "ENVELOPE(79.257732, 92.742268, 34.178571, 26.339286)",
  "dcat_bbox": "ENVELOPE(79.257732, 92.742268, 34.178571, 26.339286)",
  "dct_source_sm": ["princeton-j098zd574"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "GeoTIFF",
  "dct_references_s": "{\"http://schema.org/url\":\"https://catalog.princeton.edu/catalog/9971226563506421\",\"http://schema.org/downloadUrl\":[{\"label\":\"GeoTIFF\",\"url\":\"https://figgy.princeton.edu/downloads/67d9ca18-49ee-44a6-8d87-3d4cbc70b0c5/file/a95c7f34-d4a8-49a5-a51a-ad782e43b37a\"}],\"http://schema.org/thumbnailUrl\":\"https://figgy.princeton.edu/downloads/67d9ca18-49ee-44a6-8d87-3d4cbc70b0c5/file/8b9b0834-0f3e-48ef-95d0-e065b30cd231\",\"https://github.com/cogeotiff/cog-spec\":\"https://geodata.lib.princeton.edu/13/f5/58/13f5582c32a54be98fc2982077d0456e/display_raster.tif\"}",
  "schema_provider_s": "Princeton",
  "gbl_mdModified_dt": "2024-01-30T21:42:24Z",
  "gbl_mdVersion_s": "Aardvark",
  "gbl_suppressed_b": false,
  "gbl_resourceType_sm": ["Raster data"],
  "dct_subject_sm": [
    "Himalaya Mountains—Discovery and exploration—Maps",
    "Tibet—Discovery and exploration—Maps",
    "Physical geography—Himalaya Mountains—Maps",
    "Great Trigonometrical Survey of India",
    "Himalaya Mountains—Maps",
    "Tibet Autonomous Region (China)—Maps",
    "India, Northeastern—Maps",
    "Physical maps",
    "Maps"
  ]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/cornell_html_metadata.json
{
  "dct_title_s": "Air Monitoring Stations, Adirondack Park, 2000",
  "dct_alternative_sm": ["cornell_html_metadata"],
  "dct_description_sm": [
    "Point dataset with WMS, WFS, direct download, and FGDC metadata XML and HTML. ",
    "This dataset shows the location of each ambient air quality monitoring station currently being operated by the Bureau of Air Quality Surveillance (BAQS), Division of Air Resources, New York State Department of Environmental Conservation."
  ],
  "dct_creator_sm": ["New York State Department of Energy Conservation Bureau of Air Quality Surveillance"],
  "dct_publisher_sm": ["Geographic Data Presentation Form: Map"],
  "schema_provider_s": "Cornell",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Point data"],
  "dct_subject_sm": [
    "Air quality monitoring stations",
    "Air quality management",
    "Air--Pollution--Measurement",
    "New York State--Dept Energy Conservation"
  ],
  "dcat_theme_sm": ["Environment", "Climate"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2000-Pres"],
  "dct_issued_s": "2000-06-00",
  "gbl_indexYear_im": [2000],
  "gbl_dateRange_drsim": ["[2000 TO *]"],
  "dct_spatial_sm": ["New York"],
  "locn_geometry": "ENVELOPE(-74.989258,-73.858335,44.67778,43.452994)",
  "dcat_bbox": "ENVELOPE(-74.989258,-73.858335,44.67778,43.452994)",
  "dcat_centroid": "44.065387,-74.42379650000001",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "gbl_fileSize_s": "0.07 MB",
  "gbl_wxsIdentifier_s": "cugir007741",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://s3.amazonaws.com/cugir-data/00/77/41/cugir-007741.zip\",\"http://www.opengis.net/cat/csw/csdgm\":\"https://s3.amazonaws.com/cugir-data/00/77/41/fgdc.xml\",\"http://www.w3.org/1999/xhtml\":\"https://s3.amazonaws.com/cugir-data/00/77/41/fgdc.html\",\"http://www.opengis.net/def/serviceType/ogc/wfs\":\"https://cugir.library.cornell.edu/geoserver/cugir/wfs\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://cugir.library.cornell.edu/geoserver/cugir/wms\"}",
  "id": "cugir-007741",
  "dct_identifier_sm": ["https://cugir.library.cornell.edu/catalog/cugir-007741"],
  "gbl_mdModified_dt": "2021-06-01T22:14:15Z",
  "gbl_mdVersion_s": "Aardvark"
}
